# Generated by Django 4.2.4 on 2023-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_flight_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(to='airport.crew'),
        ),
    ]
